<!DOCTYPE html>
<html>
<head>
    <title>Welcome EnterPrise Resourse Portal</title>
</head>

<body>
<h2>New Expense Generated By {{$data['name']}},</h2>
<br/>
You have been successfully registered. Below are the OTP to confirm your registration.
<br/>
<b>Message: </b> {{ $data['message'] }}
</body>
</html>