<!DOCTYPE html>
<html>
<head>
	<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</head>
    <title>Welcome EnterPrise Resource Portal</title>
</head>

<body>
<h3>New Expense Generated By {{$data['name']}},</h3>
<br/>
Generate New Expense See Details Please Login On Dashboard Click On Bellow Link..
<br/><br/>
<a class="btn btn-primary" href="http://techconfer.in/erp/public/login" role="button">EnterPriseResourcePortal/Generate/NewExpense</a>
<br/>
<b>Message: </b> {{ $data['message'] }}
</body>
</html>